### PR TITLE
PNT-32 Extra endpoints / Cleaning up the api

### PR DESCRIPTION
**Pull request by MitchellBerry**
[API docs online](https://documenter.getpostman.com/view/8077847/SVSKM98Y?version=latest)

Adds:

-  extra endpoints

- cleaner naming system

-  exported functions which may be of use to someone

- reasonably meaningful comments

References:
 - pegnet/pegnet#32
 - pegnet/pegnet#40

Still needed short-term:

- Tests! 

- Raw to PNT address conversions

### CODE REVIEW

**Comment by PaulBernier** [comment]
Thank you for putting a high level API doc together, makes it so much easier to review the interface without the details of the code. I will discuss the API purely from the doc as I cannot think of a better place to discuss the interfaces. I haven't look at the code yet.

1. `all-oprs`: "all" with what bounds? All OPRs ever submitted by anyone? Unbounded queries are generally not very usable. Probably need either some filters or some pagination.
2. `chainid`: is that the chain the OPRs are written in? The chain of transactions? Should that method be more explicit in its name, or rather more generic and allow to query different chain ids?
3. `current-rates` returns an OPR, that's rather counter intuitive? Is that different from `winning-opr`? If I understand correctly this actually returns the last winning OPR. So 2 choices: change the API name to directly `winner` (and remove the current winner API that only returns a hash that requires another query) or keep that name but return a shape that actually contains just the latest rates.
4. `leaderheight`: I actually think that all APIs that return "latest X" (`winner`, `winners`...) should be returned with a timestamp (of the block) and the corresponding height. It's not optimal to have to make extra queries to this API to get the height plus it opens up race conditions. With those changes this `leaderheight` API may not be as useful but it doesn't hurt either.
5. I see you started introducting a shorthash. Why did you feel you need thatt? Is see some APIs take shorthash other take full hashes, and you have to make some conversions between them, it's more confusing than beneficial from a user point of view, but maybe I am missing something.
6. ` oprs-by-id ` most likely need to be paginated.

**Comment by MitchellBerry** [comment]
### Pagination:

Certainly, originally had this planned along with a mechanism for the user to restrict concurrency but ended up steamrolling through. Some of the other calls are quite hefty also and will need it too.  

`all-oprs` is essentially the biggest chunk of state stored by the miner right now. Not sure how long it will stay like that underneath, most likely it will move out into the database. It's only going to grow larger regardless. 

How useful the call is in future I'm not sure.

### Chainid:

The one OPRs are written to. 

### Current-rates:

Yep, you are right, they are exactly the same, my mistake, didn't strip out the extraneous data. The name of the call should really line up with what is produced, the naming in general could be better. 

### Leaderheight:

Somewhat redundant call as pegnet needs access to factomd anyway. 

### Shorthash:

Shorthash is simply what I called it there, for interacting with opr's it's a common element and is the only hash natively exported from the structs. A more ideal situation is being able to handle the OPR/Entry/ShortEntry hashes at once and not having to separate them out.

Changing this to v0 or avoiding api versioning altogether for now might be the best idea.

**Comment by MitchellBerry** [comment]
available at `localhost:8099/v0`

Docs are up:

https://documenter.getpostman.com/view/8077847/SVSKM98Y?version=latest

**Comment by MitchellBerry** [comment]
Going to close this while everything plays out, might plug away on it on my own fork. May resubmit depending on how quickly alternatives arise.

**Comment by Cahl-Dee** [comment]
@MitchellBerry is this closed because of the ongoing discussion regarding whether or not we will have the FAT API available?

**Comment by MitchellBerry** [comment]
Yes it was put on hold because of FAT integration. 

The current api isn't in a fully functioning state and this had a few fixes for that but there was a lot of discussion about where exactly the api would be getting served from.

**Comment by MitchellBerry** [comment]
Does FAT have any api code for pegnet I can view or is it more a hypothetical situation at the moment?

I will reopen this PR in one week from now, very keen for any alternatives offered up.

**Pull request closed without merging**
