### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by PaulSnow**
Master has not been updated in a very long time.  Looking to update and start the TestNet

### CODE REVIEW

**Comment by MitchellBerry** [comment]
Can you tag this release to test the build deployment?  Unsure if it will work.

The process is:
```git commit -m "release build v0.0.3"
git tag v0.0.3 # or anything
git push origin
git push origin tag v0.0.3
```

and that hopefully sets off a build process that uploads to the releases page

**Comment by Emyrk** [comment]
Ah I mean't to comment. Well, we should tag it yes

**Comment by MitchellBerry** [comment]
It will build once tagged with no regard for branch, so I guess leave until after it's merged.

**Comment by Emyrk** [comment]
So we can merge than tag? As the merge commit counts a new commit

**Comment by MitchellBerry** [comment]
Yes, merge first then create a tagged commit.

Interested to see if it works, not sure about deploy rights on the repo.

We can always build manually, but think this is a clean and open way to build binaries for people.

Deploying anything pushed to master on the releases page automatically might be better. Really depends on how we intend to use the branch. For now its tagged commits.

**Pull request merged**
