### PR TITLE
Incorporate the address into the duplicate check

### PR DESCRIPTION
**Pull request by WhoSoup**
Pull request for https://github.com/pegnet/pegnet/issues/110

### CODE REVIEW

**Comment by MitchellBerry** [comment]
Support this in the checks.

Guess more work still needed to nullify the entire attack vector though, great that it costs a lot more now.

**Comment by Emyrk** [comment]
Travis is failing, can you fix the unit tests that failed?

**Comment by MitchellBerry** [comment]
Failing test:

`grading_test.go:77: RemoveDuplicateMiningIDs() = wrong entry at position 0. got = a2, want = a1`

Was a bit hesitant including go test and race condition testing in the build checks, but think it is for the best.

**Comment by WhoSoup** [comment]
> Failing test:

yeah, the problem with this test is that it's iterating over a map (random) and then trying to sort it back into an expected order, so sometimes i run tests and they're fine and then run them again and they're broken. i'll have to spend some time reworking the test itself rather than trying to apply a quick fix

**Comment by WhoSoup** [comment]
looks like the test finally passed

**Comment by WhoSoup** [comment]
closing on account of not filtering duplicates anymore

**Pull request closed without merging**
