### PR TITLE
CLI Consolidation & General Restructuring

### PR DESCRIPTION
**Pull request by sambarnes**
In response to https://github.com/pegnet/pegnet/issues/21 around creating a separate cli tool to interact with nodes, I think it makes more sense to take the same approach as some other blockchain nodes and have the normal-node/miner-node/wallet all accessible in a single binary.

So I started a reorganization where the entry point is through `pegnet/main.go` and the [cobra package](https://github.com/spf13/cobra) handles the routing of which code paths / components to run.

For example:
-  `pegnet` would run just a validator node (unless overriden in config file to make it a miner
-  `pegnet --miners=8` would run a mining node with 8 miners
- `pegnet createchains` would initialize the various network chains

And we could add `pegnet wallet SUBCOMMAND` for anything we want to add for quick RPC call access

(Aside: I think a better structure might be putting `main.go` in the root of the repo, and move `cmd` folder up a level. And have `pegnetMining` renamed to `miner`, and moving the `opr/oneminer.go` into the `miner` package since its the worker.)

Edit: I see travis failed, I'll update the yaml if people like this new structure

### CODE REVIEW

**Comment by MitchellBerry** [comment]
Do like this direction, is there certain miner daemon api endpoints you are looking for?

There's no real reason for main to be in a separate folder, it breaks `go get` just for starters and requires some ide config changes (for me at least)

As for the branch build failing, if anyone is keen the logs here: https://travis-ci.com/pegnet/pegnet/jobs/214467407
Halted before it could begin, seems to be struggling with git?

**Comment by sambarnes** [comment]
@MitchellBerry thanks for checking it out, I agree that main should be moved to the root. Just commited that change.

I did also just update the travis file to just build from root, so that issue is fixed. But I think it broke before that by trying to grab the git branch from pegnet/pegnet instead of sambarnes/pegnet. Unsure though

As for the API endpoints. I'm not sure, likely just balances for now. This ticket is more about just facilitating easy cli access of those endpoints you and rafael are working on

**Comment by WhoSoup** [comment]
i like the idea as a whole

not sure if initialization should be in there since that's something nobody will likely ever run once pegnet is released. it's like a developer-only setting?

**Comment by sambarnes** [comment]
@WhoSoup hmm yeah I think that makes more sense, I'll put it back as its own main package

**Pull request merged**
